---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: "Update apt cache if needed."
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install aptitude - preferred for ansible"
      apt:
        state: latest
        name:
          - aptitude

    - name: "Update all packages to the latest version"
      apt:
        upgrade: dist

  tasks:
    - name: "Install apt cmd line apps"
      apt:
        state: latest
        name:
          - awscli
          - dos2unix
          - gnupg
          - golang
          - graphviz
          - jq
          - neofetch
          - net-tools
          - nmap
          - silversearcher-ag
          - tree
          - unzip
          - zip

    - name: "Terraform download."
      get_url:
        url: "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip"
        dest: "/tmp/terraform_0.12.29_linux_amd64.zip"
        checksum: "sha256:872245d9c6302b24dc0d98a1e010aef1e4ef60865a2d1f60102c8ad03e9d5a1d"

    - name: "Terraform install"
      unarchive:
        src: "/tmp/terraform_0.12.29_linux_amd64.zip"
        dest: "/usr/local/bin"
        remote_src: true
        creates: "/usr/local/bin/terraform"

  post_tasks:
    - name: "apt autoclean && autoremove"
      apt:
        autoclean: yes
        autoremove: yes
