---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: "Update apt cache if needed."
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install aptitude - preferred for ansible"
      apt:
        state: latest
        name:
          - aptitude

    - name: "Update all packages to the latest version"
      apt:
        upgrade: dist

  tasks:
    - name: "Install apt cmd line apps"
      apt:
        state: latest
        name:
          - awscli
          - dos2unix
          - gnupg
          - golang
          - graphviz
          - jq
          - neofetch
          - net-tools
          - nmap
          - silversearcher-ag
          - tree
          - unzip
          - zip

  post_tasks:
    - name: "apt autoclean && autoremove"
      apt:
        autoclean: yes
        autoremove: yes
