- name: "tfenv - git clone."
  git:
    repo: 'https://github.com/tfutils/tfenv.git'
    dest: '${HOME}/.tfenv'

- name: "tfenv - set path in bashrc"
  lineinfile:
    path: '${HOME}/.bashrc'
    state: present
    line: 'export PATH="$HOME/.tfenv/bin:$PATH"'
